CREATE TABLE GARAGE (
    NUM INT,
    CODE INT,
    TYPE VARCHAR(100),
    NORUE INT,
    RUE VARCHAR(100),
    VILLE VARCHAR(100),
    PRIMARY KEY (NUM),
    FOREIGN KEY (CODE) REFERENCES LOGEMENT (CODE),
    FOREIGN KEY (NORUE, RUE, VILLE) REFERENCES ADRESSE (NORUE, RUE, VILLE)
);