CREATE TABLE LOGEMENTS (
    CODE INT,
    TYPE VARCHAR(100),
    NBPIECES INT,
    SURFACE FLOAT,
    ETAT VARCHAR(100),
    OBJECTIF VARCHAR(100),
    PRIX FLOAT,
    DISPO VARCHAR(100),
    DATEDISPO DATE,
    NORUE INT,
    RUE VARCHAR(100),
    VILLE VARCHAR(100),
    NOM VARCHAR(100),
    PRENOM VARCHAR(100),
    PRIMARY KEY (CODE),
    FOREIGN KEY (NORUE, RUE, VILLE) REFERENCES ADRESSE (NORUE, RUE, VILLE),
    FOREIGN KEY (NOM, PRENOM) REFERENCES PROPRIETAIRE (NOM, PRENOM)
);
ALTER TABLE LOGEMENTS RENAME TO LOGEMENT;
ALTER TABLE Logement MODIFY Dispo VARCHAR(100);
UPDATE Logement SET Prix = Prix * 0.9 WHERE Type = 'maison';

