CREATE DATABASE IF NOT EXISTS Project1;
USE Project1;
CREATE TABLE ADRESSE (
    NORUE INT,
    RUE VARCHAR(100),
    VILLE VARCHAR(100),
    PRIMARY KEY (NORUE, RUE, VILLE)
);

CREATE TABLE PROPRIETAIRE (
    NOM VARCHAR(100),
    PRENOM VARCHAR(100),
    NORUE INT,
    RUE VARCHAR(100),
    VILLE VARCHAR(100),
    PRIMARY KEY (NOM, PRENOM),
    FOREIGN KEY (NORUE, RUE, VILLE) REFERENCES ADRESSE (NORUE, RUE, VILLE)
);

CREATE TABLE LOGEMENT (
    CODE INT,
    TYPE VARCHAR(100),
    NBPIECES INT,
    SURFACE FLOAT,
    ETAT VARCHAR(100),
    OBJECTIF VARCHAR(100),
    PRIX FLOAT,
    DISPO VARCHAR(100),
    DATEDISPO DATE,
    NORUE INT,
    RUE VARCHAR(100),
    VILLE VARCHAR(100),
    NOM VARCHAR(100),
    PRENOM VARCHAR(100),
    PRIMARY KEY (CODE),
    FOREIGN KEY (NORUE, RUE, VILLE) REFERENCES ADRESSE (NORUE, RUE, VILLE),
    FOREIGN KEY (NOM, PRENOM) REFERENCES PROPRIETAIRE (NOM, PRENOM)
);

CREATE TABLE CLIENT (
    NOM VARCHAR(100),
    PRENOM VARCHAR(100),
    NORUE INT,
    RUE VARCHAR(100),
    VILLE VARCHAR(100),
    PRIMARY KEY (NOM, PRENOM),
    FOREIGN KEY (NORUE, RUE, VILLE) REFERENCES ADRESSE (NORUE, RUE, VILLE)
);

CREATE TABLE GARAGE (
    NUM INT,
    CODE INT,
    TYPE VARCHAR(100),
    NORUE INT,
    RUE VARCHAR(100),
    VILLE VARCHAR(100),
    PRIMARY KEY (NUM),
    FOREIGN KEY (CODE) REFERENCES LOGEMENT (CODE),
    FOREIGN KEY (NORUE, RUE, VILLE) REFERENCES ADRESSE (NORUE, RUE, VILLE)
);

CREATE TABLE TRANSACTION (
    CODE INT,
    NOMP VARCHAR(100),
    PRENOMP VARCHAR(100),
    NORUEP INT,
    RUEP VARCHAR(100),
    VILLEP VARCHAR(100),
    NOMC VARCHAR(100),
    PRENOMC VARCHAR(100),
    NORUEC INT,
    RUEC VARCHAR(100),
    VILLEC VARCHAR(100),
    DATE DATE,
    COMMISSION FLOAT,
    MONTANT FLOAT,
    TYPE VARCHAR(100),
    PRIMARY KEY (CODE, DATE),
    FOREIGN KEY (CODE) REFERENCES LOGEMENT (CODE),
    FOREIGN KEY (NOMP, PRENOMP) REFERENCES PROPRIETAIRE (NOM, PRENOM),
    FOREIGN KEY (NORUEP, RUEP, VILLEP) REFERENCES PROPRIETAIRE (NORUE, RUE, VILLE),
    FOREIGN KEY (NOMC, PRENOMC) REFERENCES CLIENT (NOM, PRENOM),
    FOREIGN KEY (NORUEC, RUEC, VILLEC) REFERENCES CLIENT (NORUE, RUE, VILLE)
);

CREATE TABLE VISITE (
    CODE INT,
    NOM VARCHAR(100),
    PRENOM VARCHAR(100),
    NORUE INT,
    RUE VARCHAR(100),
    VILLE VARCHAR(100),
    DATE DATE,
    PRIMARY KEY (CODE, NOM, PRENOM, NORUE, RUE, VILLE),
    FOREIGN KEY (CODE) REFERENCES LOGEMENT (CODE),
    FOREIGN KEY (NOM, PRENOM) REFERENCES CLIENT (NOM, PRENOM),
    FOREIGN KEY (NORUE, RUE, VILLE) REFERENCES ADRESSE (NORUE, RUE, VILLE)
);
ALTER TABLE LOGEMENT RENAME COLUMN DISPO TO DISPO;
UPDATE LOGEMENT SET PRIX = PRIX * 0.9 WHERE TYPE = 'maison';
ALTER TABLE TRANSACTION ADD COLUMN ETIQUETTE VARCHAR(100);