CREATE TABLE PROPRIETAIRE (
    NOM VARCHAR(100),
    PRENOM VARCHAR(100),
    NORUE INT,
    RUE VARCHAR(100),
    VILLE VARCHAR(100),
    PRIMARY KEY (NOM, PRENOM),
    FOREIGN KEY (NORUE, RUE, VILLE) REFERENCES ADRESSE (NORUE, RUE, VILLE)
);