CREATE TABLE TRANSACTION (
    CODE INT,
    NOMP VARCHAR(100),
    PRENOMP VARCHAR(100),
    NORUEP INT,
    RUEP VARCHAR(100),
    VILLEP VARCHAR(100),
    NOMC VARCHAR(100),
    PRENOMC VARCHAR(100),
    NORUEC INT,
    RUEC VARCHAR(100),
    VILLEC VARCHAR(100),
    DATE DATE,
    COMMISSION FLOAT,
    MONTANT FLOAT,
    TYPE VARCHAR(100),
    PRIMARY KEY (CODE, DATE),
    FOREIGN KEY (CODE) REFERENCES LOGEMENT (CODE),
    FOREIGN KEY (NOMP, PRENOMP) REFERENCES PROPRIETAIRE (NOM, PRENOM),
    FOREIGN KEY (NORUEP, RUEP, VILLEP) REFERENCES PROPRIETAIRE (NORUE, RUE, VILLE),
    FOREIGN KEY (NOMC, PRENOMC) REFERENCES CLIENT (NOM, PRENOM),
    FOREIGN KEY (NORUEC, RUEC, VILLEC) REFERENCES CLIENT (NORUE, RUE, VILLE)
);
ALTER TABLE TRANSACTION ADD ETIQUETTE VARCHAR(100);
SAVEPOINT transaction_etiquette;
ROLLBACK TO SAVEPOINT transaction_etiquette;
COMMIT;


