CREATE TABLE VISITE (
    CODE INT,
    NOM VARCHAR(100),
    PRENOM VARCHAR(100),
    NORUE INT,
    RUE VARCHAR(100),
    VILLE VARCHAR(100),
    DATE DATE,
    PRIMARY KEY (CODE, NOM, PRENOM, NORUE, RUE, VILLE),
    FOREIGN KEY (CODE) REFERENCES LOGEMENT (CODE),
    FOREIGN KEY (NOM, PRENOM) REFERENCES CLIENT (NOM, PRENOM),
    FOREIGN KEY (NORUE, RUE, VILLE) REFERENCES CLIENT (NORUE, RUE, VILLE)
);